name: game_services_firebase_auth_example
description: Demonstrates how to use the game_services_firebase_auth plugin.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: 1.18.0
  firebase_auth: 3.3.20
  firebase_core_platform_interface: 4.4.1 

  game_services_firebase_auth:
    path: ../

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true